name: Build on Tag Push

on:
  push:
    tags:
      - "v*" # Matches any tag

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Install dependencies
        run: go mod download

      - name: Build binary
        run: |
          go build -o timescaledb-parallel-copy cmd/timescaledb-parallel-copy/main.go

      - name: Test version
        run: |
          TAG_NAME=${{ github.ref_name }}
          OUTPUT=$(./timescaledb-parallel-copy --version)
          echo "$OUTPUT"

          # Check if the version output contains the Git tag
          echo "$OUTPUT" | grep "$TAG_NAME" || (echo "Version output does not contain the Git tag: $TAG_NAME" && exit 1)
